using System;
using System.Collections.Generic;
using BooksShop.Contracts;
using BooksShop.Models;
using System.Linq;

namespace BooksShop
{
    public class MockBookRepository : IBookRepository
    {
        private readonly ICategoryRepository _categoryRepository = new MockCategoryRepository();
        public IEnumerable<Book> Books
        {
            get
            {
                return new List<Book>
                {
                    new Book {BookId = 1,  Name = "How I Play Golf", Author = "Tiger Woods", Price = 9.65M, ShortDescription = "For the first time, champion Tiger Woods reveals the five secrets to his amazing success--a combination of physical, metaphysical and psychological practices he uses daily to keep his game in top shape. Photos.", LongDescription = "No athlete has changed his sport the way Tiger Woods has transformed the world of golf. The Tiger phenomenon has created a new legion of golfers, seduced by Woods's almost effortless mastery of this most difficult game. In How I Play Golf Woods reveals the many facets of his game and offers a plethora of tips and advice aimed at all levels of play. Unlike most golf guides, and perhaps somewhat surprising from a player best known for his long game, How I Play Golf begins with the short game--putting, chipping, and pitching--before moving onto swing mechanics and hitting off the tee. Produced in conjunction with the editors of Golf Digest, the book is lavishly photographed and illustrated and offers a gold mine of useful ideas and mental images Tiger has collected over the years. Throughout, Tiger recounts memorable shots from his relatively brief career; for example, his only \"perfect\" shot (a 3-wood on No. 14 at St. Andrews) and his first putt at the 1995 Masters (a 20-footer for birdie on No. 1 that missed and rolled off the green). How I Play Golf is not only a first-rate instructional guide, it also communicates a passion and respect for the game that beginners, hackers, and low handicappers should find inspiring.", ImageThumbnailUrl = "https://images-na.ssl-images-amazon.com/images/I/51NlHOXqxPL._SX414_BO1,204,203,200_.jpg", ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/51NlHOXqxPL.jpg", IsBookOfTheWeek = false, InStock = true, Category = _categoryRepository.Categories.ToList()[0]},
                    new Book {BookId = 2,  Name = "THE IRISH COWBOY: A tale of lost love, regret, and personal redemption... ", Author = "D.W. Ulsterman", Price = 9.65M, ShortDescription = "A touching, heartfelt tale of lost love, regret, and personal redemption.", LongDescription = "Hap Wilkes is a spiritually fractured Montana rancher facing a painful past, an increasingly uncertain future, who now fights with everything left in a broken and failing body to keep the one thing still left to him - his pride. The Irish Cowboy is a family drama spanning decades from the time of lost love, to a family found, and finally spiritual redemption and the always-present human yearning for love and forgiveness that marks the most personal novel to date from bestselling author D.W. Ulsterman.", ImageThumbnailUrl = "https://images-na.ssl-images-amazon.com/images/I/41HQ7FqSQGL.jpg", ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/71EDI7JOxqL.jpg", IsBookOfTheWeek = false, InStock = true, Category = _categoryRepository.Categories.ToList()[1]},
                    new Book {BookId = 2,  Name = "The Last Paradise", Author = "Antonio Garrido", Price = 4.66M, ShortDescription = "With pitch-perfect period dialogue, clothing, and characterization that make the novel read like a Spielberg film, The Last Paradise hurtles forward, hugging the curves along the way. The Ford Model A Jack drives so wildly along the bumpy roads of the USSR symbolized freedom for those who could afford it, launching a global obsession and creating jobs for men like Jack. In many ways Jack is the Model A of heroes: elegantly appointed, dependable, ready to take off.", LongDescription = "Jack Beilis once lived the American dream: custom suits, new cars, and the best clubs. But by 1931, he has sunk so low he cannot feed himself or his ailing father. Now he barely has time to wipe the blood from his hands before he finds himself on a ship from New York to Moscow, running from a crime he never intended.", ImageThumbnailUrl = "https://images-na.ssl-images-amazon.com/images/I/51Zv4-S0bdL.jpg", ImageUrl = "https://www.google.bg/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjjv7rwhPXSAhVHuBoKHdUmCZ0QjRwIBw&url=https%3A%2F%2Fwww.fantasticfiction.com%2Fg%2Fantonio-garrido%2Flast-paradise.htm&bvm=bv.150729734,d.bGs&psig=AFQjCNFJbOBj8EFgvOA9DHhf70fXkdQ1sg&ust=1490647513346486", IsBookOfTheWeek = true, InStock = true, Category = _categoryRepository.Categories.ToList()[2]},
                    new Book {BookId = 3,  Name = "Men in Green", Author = "Michael Bamberger", Price = 7.17M, ShortDescription = "Surprisingly candid...Bamberger doesn’t flinch at portraying the Tour’s earthier aspects...But the book is overwhelmingly a love song.", LongDescription = "Until roughly the mid-1980s, the PGA Tour really was a tour, not the geographically-dispersed collection of big-money events that it is today. The players and often their wives drove from event to event or hopped on chartered flights together. . . . In a new book, Men in Green, author Michael Bamberger re-creates that tour through a series of surprisingly candid interviews with players, caddies, wives, and others who were there. It is a world of booze-fueled friendships and feuds, of deep bonds and annoyances, of hurts that still fester and memories that still glow. Braiding it all together is the power and addiction of golf. . . . Bamberger doesn’t flinch at portraying the Tour’s earthier aspects. Drugs, sex, and alcohol, although not sensationalized, take their appropriate place in his narrative. But the book is overwhelmingly a love song. . . . Above all, what comes through is the sense of the Tour back then as an extended family, sometimes dysfunctional but never dull.", ImageThumbnailUrl = "https://images-na.ssl-images-amazon.com/images/I/51tBjouK4RL._SX329_BO1,204,203,200_.jpg", ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/91wt7a7Ti1L.jpg", IsBookOfTheWeek = true, InStock = true, Category = _categoryRepository.Categories.ToList()[0]}
                };
            }
        }

        public IEnumerable<Book> BooksOfTheWeek { get; }

        public Book GetBookById(int bookId)
        {
            throw new NotImplementedException();
        }
    }
}